@echo off
REM Generated by Claude Sonnet 4 (Anthropic)
setlocal

REM Get the directory where this script is located
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

REM Function to find Visual Studio installation
call :FindVisualStudio
if errorlevel 1 (
    echo Error: Could not find Visual Studio installation
    echo Please ensure Visual Studio 2019 or later is installed
    pause
    exit /b 1
)

REM Set up MSVC environment
echo Setting up MSVC environment...
call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
if errorlevel 1 (
    echo Error: Failed to set up MSVC environment
    pause
    exit /b 1
)

REM Change to src-tauri directory
cd /d "%SCRIPT_DIR%\src-tauri"
if errorlevel 1 (
    echo Error: Could not change to src-tauri directory
    pause
    exit /b 1
)

REM Build the Tauri application
echo Building Tauri application for Windows...
cargo tauri build --no-bundle
if errorlevel 1 (
    echo Error: Tauri build failed
    pause
    exit /b 1
)

echo Build completed successfully!

REM Run the repack script
echo Running repack script...
powershell -ExecutionPolicy Bypass -File "%SCRIPT_DIR%\windows-repack-test.ps1"
if errorlevel 1 (
    echo Warning: Repack script failed, but build was successful
)

pause
exit /b 0

REM Function to find Visual Studio installation
:FindVisualStudio
REM Check for Visual Studio 2022
if exist "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files\Microsoft Visual Studio\2022\Community"
    goto found
)
if exist "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional"
    goto found
)
if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
    goto found
)

REM Check for Visual Studio 2019
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
    goto found
)
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
    goto found
)
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
    goto found
)

REM Check for Visual Studio Build Tools
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
    goto found
)
if exist "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" (
    set "VS_PATH=C:\Program Files\Microsoft Visual Studio\2022\BuildTools"
    goto found
)

REM Visual Studio not found
exit /b 1

:found
echo Found Visual Studio at: %VS_PATH%
exit /b 0
