# Generated by Claude Sonnet 4 (Anthropic)
# Windows repack script for subtle

# Get the directory where this script is located
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Extract version from package.json
try {
    $PackageJson = Get-Content "$ScriptDir\package.json" | ConvertFrom-Json
    $Version = $PackageJson.version
    Write-Host "Detected version: $Version" -ForegroundColor Green
} catch {
    Write-Error "Could not extract version from package.json: $_"
    exit 1
}

# Determine executable directory
$ExecutableDir = "$ScriptDir\src-tauri\target\release"
$ExecutablePath = "$ExecutableDir\subtle.exe"

if (-not (Test-Path $ExecutableDir)) {
    Write-Error "Executable directory not found: $ExecutableDir"
    exit 1
}

if (-not (Test-Path $ExecutablePath)) {
    Write-Error "Executable not found: $ExecutablePath"
    exit 1
}

Write-Host "Using executable path: $ExecutableDir" -ForegroundColor Cyan

# Change to executable directory
Set-Location $ExecutableDir

# Create archive name
$ArchiveName = "subtle $Version windows x64.zip"

# Remove existing archive if it exists
if (Test-Path $ArchiveName) {
    Write-Host "Removing existing archive: $ArchiveName" -ForegroundColor Yellow
    Remove-Item $ArchiveName -Force
}

# Create zip file
Write-Host "Creating archive: $ArchiveName" -ForegroundColor Cyan
try {
    # Create the zip file with just the executable
    Compress-Archive -Path "subtle.exe" -DestinationPath $ArchiveName -Force
    
    Write-Host "Archive created successfully: $ArchiveName" -ForegroundColor Green
} catch {
    Write-Error "Failed to create zip file: $_"
    exit 1
}

# Reveal the zip file in Explorer
Write-Host "Revealing $ArchiveName in Explorer..." -ForegroundColor Cyan
try {
    $FullPath = Join-Path $ExecutableDir $ArchiveName
    # Use explorer /select to highlight the file without opening it
    Start-Process "explorer.exe" -ArgumentList "/select,`"$FullPath`""
} catch {
    Write-Warning "Could not reveal file in Explorer: $_"
}

Write-Host "Repackaging complete." -ForegroundColor Green
