// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Seconds } from "./Seconds";

export type AudioSamplerDeltaData = { startIndex: number, startTime: Seconds, endTime: Seconds, intensity: Array<number>, };
