// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendSubtitleRect } from "./BackendSubtitleRect";
import type { Seconds } from "./Seconds";

export type BackendSubtitleEntry = { start: Seconds, end: Seconds, rects: Array<BackendSubtitleRect>, };
