// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendSubtitleRect = { "type": "ass", content: string, } | { "type": "text", content: string, } | { "type": "unsupported" };
