// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectResult = { "type": "normal", "data": string } | { "type": "strange", "data": null } | { "type": "error", "data": string };
