// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffLine = { idxFirst: number | null, idxSecond: number | null, strings: Array<[boolean, string]>, };
