// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontStyle } from "./FontStyle";

export type FontFaceInfo = { familyName: string, postscriptName: string, realHeight: number, weight: number, stretch: number, style: FontStyle, };
