// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SolutionToken } from "./SolutionToken";

export type MatchResult = { score: number, tokens: Array<SolutionToken>, };
