// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontStyle } from "./FontStyle";

export type ResolvedFontFace = { url: string, index: number, familyName: string, fullName: string, postscriptName: string, realHeight: number, weight: number, stretch: number, style: FontStyle, };
