// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamKind } from "./StreamKind";

export type StreamDescription = { type: StreamKind, index: number, languageCode: string, codecId: string | null, };
