// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubsetResult = { encoded: string, byteSize: number, nGlyphs: number, missing: string, extension: string, };
