// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Seconds } from "./Seconds";

export type VideoSamplerDeltaData = { keyframes: Array<[Seconds, number]>, startTime: Seconds, endTime: Seconds, };
